/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package evaluacion_pr1.jcr;

/**
 *
 * @author LABORATORIOS
 */
public class Formulario_JCR extends javax.swing.JDialog {

    /**
     * Creates new form Formulario_JCR
     */
    public Formulario_JCR(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
void mostrarForm_JCR(){
    this.setVisible(true);
    this.setLocationRelativeTo(null);
    this.setResizable(false);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesHabitacion_JCR = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dniTF_JCR = new javax.swing.JTextField();
        nombreTF_JCR = new javax.swing.JTextField();
        nochesTF_JCR = new javax.swing.JTextField();
        doble_JCR = new javax.swing.JRadioButton();
        individual_JCR = new javax.swing.JRadioButton();
        suite_JCR = new javax.swing.JRadioButton();
        limpiar_JCR = new javax.swing.JButton();
        cancelar_JCR = new javax.swing.JButton();
        guardar_JCR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre y apellidos");

        jLabel2.setText("DNI / Pasaporte");

        jLabel3.setText("Noches deseadas");

        dniTF_JCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniTF_JCRActionPerformed(evt);
            }
        });

        nombreTF_JCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTF_JCRActionPerformed(evt);
            }
        });

        nochesTF_JCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nochesTF_JCRActionPerformed(evt);
            }
        });

        botonesHabitacion_JCR.add(doble_JCR);
        doble_JCR.setText("Habitacion Doble");

        botonesHabitacion_JCR.add(individual_JCR);
        individual_JCR.setText("Habitacion Individual");
        individual_JCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                individual_JCRActionPerformed(evt);
            }
        });

        botonesHabitacion_JCR.add(suite_JCR);
        suite_JCR.setText("Habitacion Suite");
        suite_JCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suite_JCRActionPerformed(evt);
            }
        });

        limpiar_JCR.setText("Limpiar");
        limpiar_JCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar_JCRActionPerformed(evt);
            }
        });

        cancelar_JCR.setText("Cancelar");
        cancelar_JCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_JCRActionPerformed(evt);
            }
        });

        guardar_JCR.setText("Guardar");
        guardar_JCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_JCRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(limpiar_JCR)
                .addGap(40, 40, 40)
                .addComponent(cancelar_JCR)
                .addGap(34, 34, 34)
                .addComponent(guardar_JCR)
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(individual_JCR)
                    .addComponent(doble_JCR)
                    .addComponent(suite_JCR)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(nochesTF_JCR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dniTF_JCR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nombreTF_JCR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreTF_JCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dniTF_JCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nochesTF_JCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(individual_JCR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doble_JCR)
                .addGap(8, 8, 8)
                .addComponent(suite_JCR)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar_JCR)
                    .addComponent(limpiar_JCR)
                    .addComponent(guardar_JCR))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dniTF_JCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniTF_JCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniTF_JCRActionPerformed

    private void nombreTF_JCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTF_JCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTF_JCRActionPerformed

    private void nochesTF_JCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nochesTF_JCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nochesTF_JCRActionPerformed

    private void suite_JCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suite_JCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suite_JCRActionPerformed

    private void guardar_JCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_JCRActionPerformed
        String nombre = null;
        String dni = null;
        int noches = 0;
        String tipo = null;
        double precio = 0F;
        boolean valido = false;
        if((nombreTF_JCR.getText().isBlank())||(dniTF_JCR.getText().isBlank())||(nochesTF_JCR.getText().isBlank())){
            javax.swing.JOptionPane.showMessageDialog(this, "Faltan datos esenciales para la reserva", "Datos faltantes", javax.swing.JOptionPane.WARNING_MESSAGE);
            
        }else{
            nombre = nombreTF_JCR.getText();
            dni = dniTF_JCR.getText();
            try {
                noches = Integer.parseInt(nochesTF_JCR.getText());
                valido = true;                
            } catch (NumberFormatException numberFormatException) {
                javax.swing.JOptionPane.showMessageDialog(this, "Introduce un número de noches","Datos erroneos", javax.swing.JOptionPane.WARNING_MESSAGE);
                valido = false;
            }
           
            if(individual_JCR.isSelected()){
                tipo = "individual";
            }else if(doble_JCR.isSelected()){
                tipo = "doble";
            }else if (suite_JCR.isSelected()){
                tipo = "suite";
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Faltan datos esenciales (tipo de habitación) para la reserva", "Datos faltantes", javax.swing.JOptionPane.WARNING_MESSAGE);
                valido = false;
            }
            if("individual".equals(tipo)){
                precio = (double) noches *5;
            }else{
                precio = (double) noches *10;
            }
            
       if(valido){ javax.swing.JOptionPane.showMessageDialog(this, "Reserva guardada \nCliente : " + nombre + "\nDNI: " + dni + "\nNoches: " + noches + "\nTipo de habitación :" + tipo + "\nFianza a pagar: " + precio + "€", "Reserva Realizada", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        }
    }
            
    }//GEN-LAST:event_guardar_JCRActionPerformed

    private void individual_JCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_individual_JCRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_individual_JCRActionPerformed

    private void cancelar_JCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_JCRActionPerformed
        limpiar_JCRActionPerformed(evt);
        this.setVisible(false);
    }//GEN-LAST:event_cancelar_JCRActionPerformed

    private void limpiar_JCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar_JCRActionPerformed
        nombreTF_JCR.setText("");
        nochesTF_JCR.setText("");
        dniTF_JCR.setText("");
        botonesHabitacion_JCR.clearSelection();
    }//GEN-LAST:event_limpiar_JCRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_JCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_JCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_JCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_JCR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Formulario_JCR dialog = new Formulario_JCR(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botonesHabitacion_JCR;
    private javax.swing.JButton cancelar_JCR;
    private javax.swing.JTextField dniTF_JCR;
    private javax.swing.JRadioButton doble_JCR;
    private javax.swing.JButton guardar_JCR;
    private javax.swing.JRadioButton individual_JCR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton limpiar_JCR;
    private javax.swing.JTextField nochesTF_JCR;
    private javax.swing.JTextField nombreTF_JCR;
    private javax.swing.JRadioButton suite_JCR;
    // End of variables declaration//GEN-END:variables
}
