/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.HeadlessException;
import java.io.*;
import javax.swing.JFileChooser;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import domHandler.DOMHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;
import org.xml.sax.SAXException;
import saxHandler.SAXHandler;

/**
 *
 * @author devXerve
 */
public class Window extends javax.swing.JFrame {
    public static DOMHandler domhandler = null;
    public static SAXHandler saxhandler = null;
    public static SAXParser saxparser;
    // public static JAXBHandler jaxbhandler = null;
    /**
     * Creates new form Window
     */
    private File file = null;
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        yearSpinner = new javax.swing.JSpinner();
        yearLabel = new javax.swing.JLabel();
        authLabel = new javax.swing.JLabel();
        authTF = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        titleTF = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        loadBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        domMI = new javax.swing.JMenuItem();
        saxMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        yearLabel.setText("Año");

        authLabel.setText("Autor");

        titleLabel.setText("Título");

        addBtn.setText("Añadir libro");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        loadBtn.setText("Cargar DOM");
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        domMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        domMI.setText("ABRIR CON DOM");
        domMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domMIActionPerformed(evt);
            }
        });
        jMenu1.add(domMI);

        saxMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saxMI.setText("ABRIR CON SAX");
        saxMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saxMIActionPerformed(evt);
            }
        });
        jMenu1.add(saxMI);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authLabel)
                    .addComponent(yearLabel)
                    .addComponent(titleLabel))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleTF)
                    .addComponent(authTF)
                    .addComponent(yearSpinner))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn)
                    .addComponent(loadBtn))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(authTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authLabel)
                            .addComponent(addBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearLabel)
                            .addComponent(loadBtn))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void domMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domMIActionPerformed
	// int opened = openFile();
       // if(opened == 0 ){
         //   domhandler = new DOMHandler(file);
        //    int processed = domhandler.loadXML();
        //    if(processed!=0){
        //        System.out.println("ha habido un error al cargar el documento XML");
        //    }
        //    jTextArea1.setText(domhandler.processDOM());
       // }else{
        //    System.out.println("Ha ocurrido un error al acceder al fichero");
       // }
    }//GEN-LAST:event_domMIActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try{
            domhandler = new DOMHandler(file);
            String year = yearSpinner.getValue().toString();
            int result = domhandler.addToDOM(titleTF.getText(), authTF.getText(),year);
            if(result !=0){
                System.out.println("Error al añadir el libro");
            }
        }catch(NullPointerException ex){
            System.out.println("El fichero no esta abierto");
        }      
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
        int opened = domhandler.loadXML();
        if(opened != 0){
            System.out.println("Error al cargar los cambios");
        }
    }//GEN-LAST:event_loadBtnActionPerformed

    private void saxMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saxMIActionPerformed
        int opened = openFile();
        SAXParserFactory factory = SAXParserFactory.newInstance();
        try {
            saxparser = factory.newSAXParser();
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(opened == 0 ){
            saxhandler = new SAXHandler();
            jTextArea1.setText(processSax());
        }
    }//GEN-LAST:event_saxMIActionPerformed
    
    private int openFile(){
        JFileChooser selector = new JFileChooser();
	selector.setMultiSelectionEnabled(false);
	int selection = selector.showOpenDialog(null);
	try {
            if(selection == JFileChooser.APPROVE_OPTION){
                file = selector.getSelectedFile();
            }else{
                return -1;
            }
	}catch(HeadlessException e){
                System.out.println(e.getMessage());
                return -1;
	} 
        return 0;
    }
    private String processSax() {
        try{
           saxhandler.file_content="";
           saxparser.parse(file,saxhandler);
           return saxhandler.file_content;
        }catch(SAXException ex){
            return "Error al parsear con SAX";
        }catch(IOException ex){
            return "Error al parsear con SAX";
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               Window window = new Window();
               windowConfig(window);
               window.setVisible(true);
            }

           private void windowConfig(Window window) {
                SpinnerNumberModel model = new SpinnerNumberModel(2026, 1900, 2026, 1);
                window.yearSpinner.setModel(model);
                window.yearSpinner.setEditor(new JSpinner.NumberEditor(window.yearSpinner, "#"));
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel authLabel;
    private javax.swing.JTextField authTF;
    private javax.swing.JMenuItem domMI;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton loadBtn;
    private javax.swing.JMenuItem saxMI;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTF;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JSpinner yearSpinner;
    // End of variables declaration//GEN-END:variables

    
}
