/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package evento;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LABORATORIOS
 */
public class TablaRegistro extends javax.swing.JFrame {

    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tablaProfesores;
    private javax.swing.JTable tablaEstudiantes;
    private DefaultTableModel modeloProfesores;
    private DefaultTableModel modeloEstudiantes;

    /**
     * Creates new form TablaRegistro
     */
    public TablaRegistro() {
        initComponents();
    }

    /**
     * Constructor que recibe las listas de visitantes separadas.
     * @param profesores Lista de visitantes que son profesores
     * @param estudiantes Lista de visitantes que son estudiantes
     */
    public TablaRegistro(ArrayList<Visitante> profesores, ArrayList<Visitante> estudiantes) {
        initComponents();
        cargarProfesores(profesores);
        cargarEstudiantes(estudiantes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Carga la lista de profesores en su JTable.
     * @param profesores Lista de visitantes profesores
     */
    public void cargarProfesores(ArrayList<Visitante> profesores) {
        modeloProfesores.setRowCount(0);
        for (Visitante v : profesores) {
            modeloProfesores.addRow(new Object[]{
                v.getNombre(),
                v.getProvincia(),
                v.getHoraLlegada(),
                v.getAla()
            });
        }
    }

    /**
     * Carga la lista de estudiantes en su JTable.
     * @param estudiantes Lista de visitantes estudiantes
     */
    public void cargarEstudiantes(ArrayList<Visitante> estudiantes) {
        modeloEstudiantes.setRowCount(0);
        for (Visitante v : estudiantes) {
            modeloEstudiantes.addRow(new Object[]{
                v.getNombre(),
                v.getProvincia(),
                v.getHoraLlegada()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}